url = jdbc:sqlserver://localhost:1433;databaseName=Grupo4_IF51002025;encrypt=true;trustServerCertificate=true
user = JA
password = 1234

/bin/
.class
/lib/
# Configuración de la base de datos
# URL de conexión a la base de datos
# user y password para la conexión
